### ISSUE TITLE
Section: Welcome

### ISSUE THREAD

**Issue by UlisesGascon** [onebeyond/cybersecurity-handbook#19]
### Todo:
- [x] Explain the guide
- [x] Add red to Contributing, CoC...
- [x] Add references to sources
- [x] Explain the sections
- [ ] Add references to hacker movies 😎
