### ISSUE TITLE
Project Roadmap

### ISSUE THREAD

**Issue by UlisesGascon** [onebeyond/cybersecurity-handbook#41]
This issue will guide us trough the growing backlog, user requests and releases. 

Note: [This is project](https://github.com/guidesmiths/cybersecurity-handbook/projects/1) that helps us to follow the day to day targets 👍 

# Current planned Releases

### High Priority
- [ ] Complete section: Attacks explained. Details: #28
- [ ] Complete section: About Cybersecurity. Details: #26
- [ ] Complete section: Checklists (Minimal version). Details: #25 
- [ ] Complete section: Testing Guides (Minimal version). Details: #16 
- [x] Complete section: Tooling. Details: #22
- [ ] Complete section: Resources. Details: #17
- [ ] Complete section: Welcome. Details: #19
- [ ] Complete section: Acknowledgments and credits. Details: #20
- [ ] Complete section: Best practices. Details: #24
- [ ] OWASP TOP 10 Refresh content and refactor to Nodejs. Details: #22
- [ ] Update Readme #21
- [ ] Basic Deploy (as /docs in GH Pages)
- [ ] We need a great banner/cover and logo (cc: @lovetacirupeca)
- [ ] Release it. See: #40 

### No priority
- [ ] Improve `expect-ct hedader` content
- [ ] Add route / with general.mdx for all sections
- [ ] Add Humor (xkcd, commit strip, Memes) 💪 
- [ ] Add license details for content at handbook level
- [ ] Open External links in a separate tab and internal links in current tab.
- [ ] Improve Styles and components (cc: @inigomarquinez & @kevinccbsg)
- [ ] Check for internal links missing (refs to content)

## Release v1.0.0 (Blue Box)
- [ ] Collect Feedback about v0.1.x 
- [ ] Add CI to deploy in a friendly URL. Details: #13
- [ ] Section: Security Design. Details: #31
- [ ] Extend Section: Checklists
- [ ] Extend Section: Testing Guides
- [ ] Proactive Controls Refactor 
  - [ ] Migrate examples to Nodejs
  - [ ] Simplify texts
- [ ] Release it. See: #30 

# Non planned yet

### Topics:
- React
- React Native
- Cloud Development (AWS, Azure, Google...)
- Serverless and JAM Stack
- [CWE TOP 25](https://cwe.mitre.org/top25/archive/2019/2019_cwe_top25.html)
- [OWASP Application Security Verification Standard](https://owasp.org/www-project-application-security-verification-standard/)
- [OWASP Web Security Testing Guide](https://owasp.org/www-project-web-security-testing-guide/)
- [OWASP SAMM](https://owasp.org/www-project-samm/)
- Conceptual:
  - [STRIDE](https://en.wikipedia.org/wiki/STRIDE_(security))
  - [DREAD (risk assessment model)](https://en.wikipedia.org/wiki/DREAD_(risk_assessment_model))
  - [CIA triad](https://en.wikipedia.org/wiki/Information_security#Key_concepts)
  - [The 10 immutable laws of security revisited](https://techtalk.gfi.com/security-101-the-10-immutable-laws-of-security-revisited/)

**Comment by UlisesGascon** [comment]
This was relocated to https://github.com/onebeyond/cybersecurity-handbook/projects/1
